#+TITLE:     A measurement of jet substructure variables in prompt J/\psi events at ATLAS
#+AUTHOR:    David Bjergaard
#+OPTIONS:   H:3 num:t toc:nil ':t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:nil
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc

#+LATEX_CLASS: dukedissertation
#+LATEX_HEADER:\supervisor{Ayana T Arce}
#+LATEX_HEADER:\department{Physics}
#+DATE: 2017
#+LATEX_HEADER:\member{Tom C. Mehen}
#+LATEX_HEADER:\member{Mark C. Kruse}
#+LATEX_HEADER:\member{Ashutosh V. Kotwal}
#+LATEX_HEADER:\member{Glenn Edwards}
#+LATEX_HEADER:\addbibresource{thesis.bib}


#+LATEX_HEADER:\hypersetup{
#+LATEX_HEADER:plainpages=false,
#+LATEX_HEADER:bookmarksnumbered,
#+LATEX_HEADER:colorlinks, linkcolor=black, citecolor=black,
#+LATEX_HEADER:filecolor=black, urlcolor=black,
#+LATEX_HEADER:}

#+INCLUDE: abstract.org
# ``Life is short,\\ 
# and art long,\\
# opportunity fleeting,\\
# experimentations perilous,\\
# and judgement difficult''\\
# -- Hippocrates \emph{Aphorismi}


#+BEGIN_LaTeX
\dedication{
To my wife.
}
#+END_LaTeX
#+BEGIN_LaTeX
\tableofcontents
\listoftables
\listoffigures
#+END_LaTeX

#+INCLUDE: acknowledgements.org

#+LaTeX: \chapter{Introduction}
* A brief history
The history of particle physics spans over a century of experimental
and theoretical development that has lead to some of the deepest
insights into nature. A comprehensive history of the subject is beyond
the scope of this document, however a starting point is required.
During the post-war period of the early 1950s a series of bubble
chamber experiments led to the discovery of the $\Lambda$, $\Xi$ and
$\Sigma$ baryons[fn::Baryons are bound states of three quarks. The
name is derived from the greek word "heavy" or "barus" ]. This coupled
with the discoveries of the $K$, $\pi$ and $\eta$ mesons[fn:: Mesons
are bound states of a quark and an anti-quark. The name is derived
from the greek word "intermediate" or "mesos" ] lead to the proposal
of the "eightfold way" \cite{PhysRev.125.1067}. The guiding principal
of the eightfold way is to use the structure of a proposed
$SU(3)\times SU(3)$ symmetry to explain the mesons and baryons known
to date and to make strong predictions about new states that should be
observed \cite{PhysRev.125.1067}. This organization of the particles
hints at the existence of fundamental particles called /quarks/.

While the eightfold way provided an organizational scheme and strong
predictions of the relationships between the members of the baryon
octet, experimental evidence for the existence of quarks came later.
In 1971, Feynman published what is now known as the parton[fn:: Parton
so called for being a "part" of the hadron. Also rumored to be named
after Dolly Parton, the country singer\cite{ashone}. ] model of the
hadron \cite{PhysRevD.3.2706}. This model treated the components of
the hadron as fundamental particles with physical properties. This is
in contrast with the quark model of the eightfold way which did not
describe quarks as physical particles. The parton model described many
experimental results to a reasonable degree however there were some
issues, namely a "fudge factor" to bring the calculations close enough
to their experimental values to be compared \cite{PhysRevD.3.2706}.

The eightfold way and the parton model provided two complementary
views of the structure of the hadron. The eightfold way provided a
computational framework that was successful in describing many
observed patterns in the quantum numbers of the known hadrons. The
parton model provided a physical picture for the structure of the
hadron. Neither model provided a precise description of the underlying
dynamics of the strong interaction.

In November, 1973 Wilczek and Gross published their seminal paper on
asymptotically free gauge theories \cite{PhysRevD.8.3633}. This paper
laid the groundwork for what would become quantum chromodynamics (QCD)
the theory underpinning the subject of this thesis. A year later in
1974 the discovery of a new particle was announced independently by a
group at Brookhaven National Lab (named the $J$) and a group at the
Stanford Linear Accelerator (named the $\psi$)
\cite{PhysRevLett.33.1404}\cite{PhysRevLett.33.1406}. The joint
discovery of the J/\psi lead to what is known colloquially as the
"November revolution." The new particle provided a new piece of
experimental evidence that confirmed the picture of quarks and helped
to unravel the mysteries of the strong interaction.

We now understand that hadrons are made up of quarks and gluons
(partons in Feynman's parlance). In addition, the bound state of a
quark and anti-quark of the same flavor are referred to as quarkonium.
This name is reminiscent of positronium, the eletromagnetically bound
state of a positron and electron. Many of the salient features of
quarkonium mass spectrum can be understood with non-relativistic
quantum mechanics and emperical models of the QCD potential. Even with
this deep understanding of nature's fundamental interactions, the
J/\psi particle continues to perplex and confuse our understanding of
QCD. In 1992, the CDF collaboration at the Tevatron reported the first
measurement of J/\psi and \psi(2S) production. They found the rate of
production to be an order of magnitude more than the expectation from
theory \cite{Abe:1992ww}. Two years later, Bodwin, Braaten and Lepage
worked out many of the details of quarkonium production in QCD using
effective field theory\cite{Bodwin:1994jh}.

In 1997, the Tevatron updated its observation of the \psi system with
more data. It reported the differential cross section of the J/\psi to
be much higher than anticipated by the leading order theory
calculation for singlet production \cite{PhysRevLett.79.572}. The
details worked out by Bodwin et al positioned the theory community to
quickly calculate the needed contributions from the non-relativistic
expansion of QCD (NRQCD) in order to describe the data
\cite{PhysRevD.55.R5269}.

The extra NRQCD components that describe the observed p_T spectrum
predicted that the spin alignment between the J/\psi and the decaying
muons be strongly polarized. Subsequent measurements of the
polarization at CDF find no evidence of polarized spin-alignment in
the J/\psi system \cite{PhysRevLett.85.2886}. This problem has been
dubbed the "polarization puzzle" in literature and has no satisfying
explanation nearly two decades after its first observation.

The production of charm quark pairs which transition to the J/\psi
state probes two complementary energy scales. The origination of the
pair happens during the primary interaction of two partons. This is a
high energy interaction, and can be calculated using perturbation
theory. After the pair of quarks is produced, their relative motion
determines the dynamics of the bound state. This is at a much lower
energy scale and is non-perturbative. Handling these two scales is the
major theoretical challenge to calculating a quantitative cross
section for quarkonium production.

While there has been much theoretical work to understand J/\psi
production, experimental approaches have mainly focused on measuring
the differential production cross section of isolated, directly
produced J/\psi particles. Little to no attention has been paid to the
hadronic environment surrounding the charmonium system. If the
charmonium is produced in a color singlet state, the surrounding
radiation should be less than a charmonium state in a color octet
state.  

A useful phenomenological model employed by Pythia [fn:: A generic
Monte Carlo simulation program used in High Energy Physics] is to
consider the charmonium system as a color-charged particle which can
couple to gluons using rules of QCD \cite{Sjostrand:2007gs}. As this
particle propogates it emits co-linear gluon radiation according to a
splitting function for the process $q\rightarrow q g$. When the
composite particle falls below a certain threshold, it transitions to
a color singlet J/\psi hadron and emits the remaining color charge as
a soft gluon which is incorporated into the underlying event. This is
in contrast to color singlet production which has the J/\psi produced
directly and no net color charge.

An alternative view of charmonium production is the production of the
charm quark pair during the fragmentation of partons into individual
hadrons. In the fragmenting jet function (FJF)
framework\cite{Procura:2009vm}, the total cross section is a product
of the short distance partonic cross section with universal
fragmentation functions which determine the evolution of individual
partons to hadrons.

The FJF framework differs from the Pythia model in how it treats the
distribution of radiation around the charmonium system.  In the FJF
approach, a high energy gluon splits according to a splitting function
for $g\rightarrow g g$, which is very different from Pythia's model
which allows the charmonium system to radiate according to a splitting
function for $q \rightarrow q g$.  This leads to fundamentally
different distributions of momentum between the surrounding radiation
and the charmonium system \cite{Bain:2016clc}.  

#+LaTeX: \chapter{Theory}
* Quantum Chromodynamics
Quantum chromodynamics describes the interactions between quarks and
gluons. It is one of the fundamental pieces of the Standard Model of
Physics, and has provided fertile ground for experimental and
theoretical work. The interactions of QCD are determined by the SU(3)
symmetry group. Under this symmetry quarks have a color charge
($a=1,2,3$). While quarks carry a color charge, they must form color
neutral particles. Therefore, it is useful to assign the colors red,
green, and blue to the color index in order to provide intuition for
which states are allowed. Quarks paired with color conjugated quarks
(green with anti-green, red with anti-red etc) form the mesons.
Triplet pairs of quarks with an anti-symmetric combination of red,
green, and blue form color neutral baryons. Other more exotic
combinations are allowed but they must follow the constraint that the
state be color neutral.
** Quark Flavor
In addition to carrying color charge, quarks carry a flavor. The
Standard Model consists of three generations of quarks. Each
generation consists of a flavor doublet with charge 2/3 and charge
-1/3. Quarks with charge 2/3(-1/3) are referred to as up(down)-type
quarks. In each generation, the mass of the quarks are successively
larger. In the first generation, the up and down quarks are a few MeV.
The strange and charm quark masses differ by a factor of 10. The
strange quark mass is approximately 100 MeV, while the charm quark
mass is near 1 GeV. In the third and final generation, the bottom
quark is 4 GeV, and the top quark is forty times larger at 173 GeV
\cite{Agashe:2014kda}. The quantum numbers of the individual quarks
determine the properties of the composite baryons and mesons.
** Lagrangian
The formulation of a quantum theory for quark interactions requires a
lagrangian which contains interaction terms which satisfy the SU(3)
symmetry group. The following summarizes the results in chapter 1 of
"QCD and Collider Physics" \cite{Ellis:1991qj}, for further details
the reader is referred to that text.

In order to derive a quantum theory, begin by writing the QCD
lagrangian in terms of a classical field plus a gauge fixing term, and
a ghost term.
#+BEGIN_LaTeX
  \begin{equation*}
    \mathcal{L}_{\text{QCD}}=\mathcal{L}_{\text{Classical}}+\mathcal{L}_{\text{Gauge}} + \mathcal{L}_{\text{Ghost}}
  \end{equation*}
#+END_LaTeX
In natural units ($\hbar=c=1$), the classical field lagrangian is:
#+BEGIN_LaTeX
  \begin{equation}
    \mathcal{L}_{\text{Classical}} = -\frac{1}{4}F^A_{\alpha\beta}F^{\alpha\beta}_A + \sum_{\text{flavors}}\overline{q}_a(i\slashed{D}-m)_{ab}q_b
  \end{equation}
#+END_LaTeX
Here $\slashed{D}\equiv\gamma_\mu D^\mu$, and $F_{\alpha\beta}^A$ is
the gluon field strength tensor:
#+BEGIN_LaTeX
  \begin{equation}
    F_{\alpha\beta}^A =
    \partial_\alpha\mathcal{A}_\beta^A-\partial_\beta\mathcal{A}_\alpha^A - g f^{ABC}\mathcal{A}_\alpha^B\mathcal{A}_\beta^C
  \end{equation}
#+END_LaTeX
The color indices $A,B,C$ run over the eight generators of the SU(3)
group. The constant $g$ represents the coupling strength, and the
constants $f^{ABC}$ are the structure constants of SU(3). It is this
term which distinguishes QCD from quantum electrodynamics (QED). In
order to derive the Feynman rules for QCD, the path integral of the
action must be evaluated. In the standard formulation of the action,
the resulting integral is badly divergent because of the gauge
invariance of the theory \cite{Peskin:1995ev} [fn:: See 9.4
Quantization of the Electromagnetic Field]. Following the
Faddeev-Popov method of gauge fixing used in \cite{Ellis:1991qj} the
following two terms are added to the lagrangian:
#+BEGIN_LaTeX
  \begin{align}
    \mathcal{L}_{\text{Gauge}} &= -
    \frac{1}{2\lambda}(\partial^\alpha\mathcal{A}_\alpha^A)^2 \\
    \mathcal{L}_{\text{Ghost}} &= \partial_\alpha\eta^{A\dagger}(D^\alpha_{AB}\eta^B)
  \end{align}
#+END_LaTeX
These terms serve to constrain the integral over the action to
physical configurations exactly once \cite{Peskin:1995ev}. 
** Feyman Rules
The Feynman rules for QCD can be determined from the lagrangian by
finding the action ($S = \int \mathcal{L} d^4x$)and writing it in
terms of a free field lagrangian $S_0$ and an interacting term $S_I$:
#+BEGIN_LaTeX
  \begin{equation*}
  S = S_0 + S_I
  \end{equation*}
#+END_LaTeX
Further by identifying $\partial^\alpha = -ip^\alpha$ as the momentum
it is possible to write down the two point function for the quarks and
gluons. This results in the Feynman rules shown in Figure
\ref{fig:qcd-feyn-rules}.
#+CAPTION: Feynman rules for QCD, see \cite{Ellis:1991qj} for more details.
#+NAME: fig:qcd-feyn-rules
#+ATTR_LATEX: :width \linewidth
[[file:figures/qcd_rules.eps]]

Combined, these rules allow the creation of any relativistic quark
interactions allowed by the theory of QCD.  There are two aspects of
QCD which distinguish it from QED. 

The first is the running of the coupling constant, $\alpha_S$. In QED,
the coupling constant is higher at high energies. This running of the
coupling constant can be understood by examining the state of the
vacuum around the electric charge. At high energies, and short
distances, there is less screening of the true charge of the electron
due to vacuum polarization. This polarization arises due to dipole
pairs of virtual electrons and positrons which screen the charge of
the electron. This leads to a coupling constant which is larger than
at low energies. In QCD, the coupling constant decreases at high
energy.  This phenomenon is known as asymptotic freedom.  At very high
energies, the coupling between quarks becomes so low that they become
free particles.  It is difficult to understand this from the vacuum of
QCD, but it is possible to make analogies to the paramagnetic
properties of the vacuum \cite{Ellis:1991qj}. 

The second feature is the self-interaction of the gluon.  In QED, the
mediating photon has no electric charge, and thus does not couple to
itself.  In QCD, the gluon carries color charge. This means that the
field doesn't spread uniformly out from the quark, instead it forms
tube-like structures.  At some point, the potential energy stored in
the self-interacting gluon tubes becomes so high that it is
energetically favorable to create a quark anti-quark pair from the
vacuum than it is to increase the distance between two quarks further.
This property of QCD is referred to as confinement. 
* Quarkonium
The bound states allowed by a theory and their properties are
important to any theory. In QCD, bound states consist of mesons and
baryons in accordance with the rules outlined in Section [[Feyman Rules]].
When a meson forms a bound state with a quark and anti-quark of the
same flavor it is referred to as a quarkonium state. This naming
scheme is reminiscent of the positronium bound state from quantum
mechanics in a coulomb potential. Quarkonium have a number of unique
properties that make it an ideal system to study properties of QCD.
The bound state consists of a quark and its charge-conjugate. This
provides a degree of symmetry not present in other meson systems. In
heavy quarkonium systems (charmonium and bottomonium), the mass scale
is high enough that perturbation theory can provide useful answers
relative to the cutoff energy scale $\Lambda_{\text{QCD}}\simeq
450~\text{MeV}$. The strength of the coupling strength of QCD in the
charmonium system is $\alpha_s(m_c)\approx0.24$ \cite{Bodwin:1994jh}. This
is large enough that the perturbation series converges more slowly
than one would hope. The higher mass of the bottom quark allows the
bottomonium system a faster rate of convergence. At the bottom mass
scale, $\alpha_s(m_b)\approx0.18$ \cite{Bodwin:1994jh}.  

Before examining the consequences of a larger $\alpha_s$ in the
charmonium system, it is useful to reproduce as much of the charmonium
spectrum using quantum mechanics. An important aspect of quarkonium
production at high energies in hadronic collisions is the interplay of
multiple energy scales. At very high energies, production is dominated
by the fragmentation of gluons into pairs of charm quarks. The gluon
recoils from a primary interaction with a gluon or quark in the
proton-proton collision. The energy scale which determines the
production of the quark pair is the mass of the heavy quark $M$.

In the rest frame of the quarkonia's constituent quarks the relative
velocity ($v$) of the quarks is the important scale. This means their
relative momentum ($Mv$) is important for the dynamics of the
quarkonium's propagation and subsequent decay. The final quantity
which determines the dynamics of the system is the kinetic energy
($Mv^2$) of the quarks. The kinetic energy determines the size of the
radial excitations in the system \cite{Bodwin:1994jh}. It is assumed
that these scales are well separated in the sense that $(Mv^2)^2 <<
(Mv)^2 << M^2$ \cite{Bodwin:1994jh}.

** Positronium System
A treatment of the positronium system can be found in any
undergraduate treatment of bound states allowed by the Coulomb
potential \cite{Townsend:2000modern} \cite{Griffiths:2008zz}. A brief
review of the important results are presented. The content of this
section follows that of \cite{Ellis:1991qj}. The existence of a
solution is due to the spherical symmetry of the coulomb potential.
This allows the system to be solved by separation of variables and
reduces the degrees of freedom to finding the one dimensional bound
states due to the coulomb potential:
#+BEGIN_LaTeX
  \begin{equation*}
    U(r) = - \alpha/r
  \end{equation*}
#+END_LaTeX
Here $\alpha$ is the dimensionless fine structure constant, and takes
a value of 1/137. The wavefunction is then written as:
#+BEGIN_LaTeX
\begin{equation}
\psi(r,\theta,\phi) = R_{l,n}(r)Y^m_l(\theta,\phi)
\end{equation}
#+END_LaTeX
Here $R_{l,n}(r)$ is the radial solution, and $Y^m_l(\theta,\phi)$ are
the spherical harmonic functions. The spherical harmonics $Y^m_l$
arise from requiring angular momentum conservation. The radial
functions are determined by finding the solutions to the
time-independent Shroedinger equation. The energy eigenvalues are the
well known Bohr energy levels:
#+BEGIN_LaTeX
\begin{equation}
E_n = - \frac{\mu\alpha^2}{2n^2}
\end{equation}
#+END_LaTeX
Here $\mu$ is the reduced mass of the system[fn:: $\mu\equiv
\frac{m_1m_2}{m_1+m_2}$, In the case of positronium this is $m_e/2$].
The characteristic length scale of the system is the Bohr radius:
#+BEGIN_LaTeX
  \begin{equation}
  a_0 = \frac{1}{\mu \alpha}
  \end{equation}
#+END_LaTeX
The ground state wave function is ($n=1,l=0,m=0$) \cite{Townsend:2000modern}:
#+BEGIN_LaTeX
\begin{equation}
\label{eq:1S1}
\psi_{100}(r,\theta,\phi) = \frac{1}{\sqrt{\pi a_0^3}}e^{-r/a_0}
\end{equation}
#+END_LaTeX
The first radial excited state is ($n=2,l=1,m=0$) \cite{Townsend:2000modern}:
#+BEGIN_LaTeX
  \begin{equation}
  \label{eq:3P0}
  \psi_{210}(r,\theta,\phi) = \frac{1}{4\sqrt{2\pi a_0^3}}\frac{r}{a_0}e^{-r/(2a_0)}\cos\theta
  \end{equation}
#+END_LaTeX
These two states are important because they correspond to the first
two excitations in the charmonium spectrum. At this point it is useful
to introduce the spectroscopic notation used in quarkonia literature.
The notation follows that of atomic spectroscopy: $^{2S+1}L_J$. Here
$S$ is the total spin of the system, $L$ is the orbital quantum
number, and $J$ is total angular momentum. In the case of positronium,
and quarkonium, the constituent particles are spin-1/2. Therefore when
they are combined $S$ can take the values of 0 or 1. The orbital
angular quantum number $L$ follows the time-honored notation where
$L=0,1,2,3,\ldots$ corresponds to the letters $S,P,D,F,\ldots$.
Finally, $J$ takes the values $J=|L-S|,\ldots,L+S$.

Up to this point the positronium system and the quarkonium system have
been treated as interchangeable. In fact, if gluons did not
self-interact, the QED potential and the QCD potential would be the
same modulo coupling constants and a numerical factor for color. This
similarity suggests that using the hydrogen-like wave-functions as a
basis state and applying perturbation theory may prove fruitful.
** Potential Models of QCD
It is not an accident that the potential model of QCD works well to
describe the distribution of bound states observed in quarkonium
systems. First, the gluon interaction times are much shorter than the
movement time scale of the quarks. This is due to the assumption that
the kinetic energy, $Mv^2$ is much smaller than the momentum of the
quarks, $Mv$\cite{Bodwin:1994jh}. This means that treating the quarks
as though they exist in an instantaneous potential is a good
approximation. The second reason potential models are successful is
the fact that the probability of another gluon existing in the bound
state is small \cite{Bodwin:1994jh}.

Using a the coulomb eigenfunctions as a set of basis states and
applying a perturbative potential provides a good description of the
quarkonium spectrum. The perturbation used is due to the
self-interaction of the gluons. 
#+BEGIN_LaTeX
\begin{equation*}
V(r)=Kr
\end{equation*}
#+END_LaTeX 
Here $K$ is the "string constant".  This term combined with the
coulomb-like potential:
#+BEGIN_LaTeX
  \begin{equation*}
    U(r) = - \frac{4}{3}\frac{\alpha_s}{r}
  \end{equation*}
#+END_LaTeX
completes the model. The perturbation is confining at large distances
and presents a constant force. The string analogy is apt, as the
tension in a string is constant. When the force applied exceeds the
tensile strength of the string, the string snaps. This analogy
suggests the string model of fragmentation in which the gluon
"strings" snap and quark anti-quark pairs form at the ends of the
strings.
#+CAPTION: Spectrum of charmonium and bottomonium bound states compared to potential theory. 
#+NAME: fig:spectrum
#+ATTR_LATEX: :width \linewidth :options angle=-90
[[file:figures/quarkonium_spectrum.eps]] 

Figure \ref{fig:spectrum} shows the result of applying a more
sophisticated potential model as a perturbation on the coulomb-like
eigenfunctions. This model has the asymptotic features of the string
model and describes the data well \cite{Ellis:1991qj}.  The dashed
lines are the theory prediction and the solid lines are the data.  The
bottomonium spectrum is better described because the mass is higher,
and hence the coupling constant is weaker making the assumptions
behind the potential model stronger. 
* Non-relativistic QCD
** Lagrangian
** Factorization Theorem
** Color Octet States

* Jet fragmentation

** Fragmentation Functions
#+LaTeX: \chapter{The ATLAS detector}
* The Large Hadron Collider
* The ATLAS detector
** Inner Detector
*** Pixel Detector
*** Silicon Strip Detector
*** Transition Radiation Tracker
** Muon Spectrometer
*** Monitored Drift Tube
*** Cathode Strip Chambers
** Track Reconstruction
** Trigger

#+LaTeX: \chapter{Event Reconstruction and Selection}
* J/\psi reconstruction
* Jet definitions
** Jet Reconstruction
#+LaTeX: \chapter{Analysis Methods}
* Fitting the data
* SPlot
* Unfolding
** Validating the Method
* Unfolding
** Iterative Bayesian Unfolding
*** Determining Iterations
*** Validating the Method
*** Estimating the Response Matrix

#+LaTeX: \chapter{Measurement of prompt J/$\psi$ particles}
* Selection Criteria
* Systematic Errors
* Results
* Discussion

#+BEGIN_LaTeX
\cleardoublepage
\normalbaselines %Fixes spacing of bibliography
\addcontentsline{toc}{chapter}{Bibliography} %adds Bibliography to your table of contents
\printbibliography
#+END_LaTeX

#+INCLUDE: biography.org
